---
- name: Installer Docker sur Ubuntu 22.04
  hosts: all
  become: yes
  tasks:

    - name: Mettre à jour le système
      apt:
        update_cache: yes
        upgrade: dist

    - name: Supprimer les fichiers obsolètes de Docker
      shell: |
        sudo apt remove -y docker-desktop || true
        rm -rf $HOME/.docker/desktop || true
        sudo rm -f /usr/local/bin/com.docker.cli || true
        sudo apt purge -y docker-desktop || true
      args:
        warn: false

    - name: Installer les paquets nécessaires pour le dépôt Docker
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Ajouter la clé GPG de Docker
      shell: |
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        warn: false

    - name: Ajouter le dépôt Docker
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable

    - name: Mettre à jour le cache des paquets après ajout du dépôt Docker
      apt:
        update_cache: yes

    - name: Installer Docker Engine et ses dépendances
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Vérifier l'installation de Docker
      command: docker run hello-world
      register: result
      failed_when: "'Hello from Docker!' not in result.stdout"
      retries: 3
      delay: 5
      ignore_errors: yes

    - name: Configurer Docker pour s'exécuter sans privilèges root (facultatif)
      block:
        - name: Créer un groupe Docker
          group:
            name: docker
            state: present

        - name: Ajouter l'utilisateur courant au groupe Docker
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        - name: Déconnexion/reconnexion pour appliquer les modifications (message)
          debug:
            msg: "Veuillez vous déconnecter/reconnecter pour que les modifications prennent effet."
      when: ansible_user != "root"
